import { DockerTopic } from "./types";
import { enrichedData } from "./data-enriched";

export type { DockerTopic }; // Re-export type

const rawTopics = [
  { id: 1, category: "Fundamentals", topic: "What is Docker?", description: "Containerization concept, VMs vs Containers" },
  { id: 2, category: "Fundamentals", topic: "Docker Architecture", description: "Docker Engine, Daemon, CLI, Desktop" },
  { id: 3, category: "Fundamentals", topic: "Installation & Setup", description: "Docker Desktop (Win/Mac), Docker Engine (Linux)" },
  { id: 4, category: "Fundamentals", topic: "Docker Hub", description: "Public registry, pulling official images" },
  { id: 5, category: "Fundamentals", topic: "Images vs Containers", description: "Difference, relationship, lifecycle" },
  { id: 6, category: "Images", topic: "Pulling Images", description: "docker pull, tags, versions" },
  { id: 7, category: "Images", topic: "Listing & Removing Images", description: "docker images, docker rmi" },
  { id: 8, category: "Images", topic: "Image Layers", description: "How layers work, read-only stacking" },
  { id: 9, category: "Images", topic: "Image Caching", description: "Build cache, cache invalidation" },
  { id: 10, category: "Images", topic: "Image Tagging", description: "docker tag, naming conventions" },
  { id: 11, category: "Images", topic: "Pushing Images", description: "docker push, Docker Hub login" },
  { id: 12, category: "Images", topic: "Image Inspection", description: "docker inspect, docker history" },
  { id: 13, category: "Containers", topic: "Running Containers", description: "docker run, flags -d, -it, --name" },
  { id: 14, category: "Containers", topic: "Listing Containers", description: "docker ps, docker ps -a" },
  { id: 15, category: "Containers", topic: "Starting & Stopping", description: "docker start, docker stop, docker restart" },
  { id: 16, category: "Containers", topic: "Removing Containers", description: "docker rm, docker container prune" },
  { id: 17, category: "Containers", topic: "Container Logs", description: "docker logs, --follow flag" },
  { id: 18, category: "Containers", topic: "Exec into Container", description: "docker exec -it <container> bash" },
  { id: 19, category: "Containers", topic: "Port Binding", description: "-p host:container, exposing ports" },
  { id: 20, category: "Containers", topic: "Container Stats", description: "docker stats, docker top" },
  { id: 21, category: "Containers", topic: "Copy Files", description: "docker cp between host and container" },
  { id: 22, category: "Containers", topic: "Container Restart Policies", description: "--restart always/unless-stopped/on-failure" },
  { id: 23, category: "Dockerfile", topic: "FROM", description: "Base image instruction" },
  { id: 24, category: "Dockerfile", topic: "RUN", description: "Execute commands during build" },
  { id: 25, category: "Dockerfile", topic: "COPY & ADD", description: "Copy files into image" },
  { id: 26, category: "Dockerfile", topic: "WORKDIR", description: "Set working directory" },
  { id: 27, category: "Dockerfile", topic: "ENV", description: "Set environment variables" },
  { id: 28, category: "Dockerfile", topic: "ARG", description: "Build-time variables" },
  { id: 29, category: "Dockerfile", topic: "EXPOSE", description: "Document container port" },
  { id: 30, category: "Dockerfile", topic: "CMD", description: "Default container command" },
  { id: 31, category: "Dockerfile", topic: "ENTRYPOINT", description: "Fixed container executable" },
  { id: 32, category: "Dockerfile", topic: "CMD vs ENTRYPOINT", description: "Key differences & when to use each" },
  { id: 33, category: "Dockerfile", topic: "VOLUME", description: "Declare mount points" },
  { id: 34, category: "Dockerfile", topic: "USER", description: "Run as non-root user" },
  { id: 35, category: "Dockerfile", topic: "LABEL", description: "Add metadata to image" },
  { id: 36, category: "Dockerfile", topic: "HEALTHCHECK", description: "Container health monitoring" },
  { id: 37, category: "Dockerfile", topic: ".dockerignore", description: "Exclude files from build context" },
  { id: 38, category: "Dockerfile", topic: "Multi-Stage Builds", description: "Smaller production images using multiple FROM" },
  { id: 39, category: "Networking", topic: "Bridge Network", description: "Default network driver" },
  { id: 40, category: "Networking", topic: "Host Network", description: "Container shares host network" },
  { id: 41, category: "Networking", topic: "None Network", description: "No networking" },
  { id: 42, category: "Networking", topic: "Overlay Network", description: "Multi-host networking (Swarm)" },
  { id: 43, category: "Networking", topic: "Custom Networks", description: "docker network create" },
  { id: 44, category: "Networking", topic: "Container DNS", description: "Containers communicate by name" },
  { id: 45, category: "Networking", topic: "Network Inspection", description: "docker network inspect" },
  { id: 46, category: "Networking", topic: "Connecting Containers", description: "--network flag, docker network connect" },
  { id: 47, category: "Storage", topic: "Volumes", description: "Docker-managed persistent storage" },
  { id: 48, category: "Storage", topic: "Bind Mounts", description: "Mount host directory into container" },
  { id: 49, category: "Storage", topic: "tmpfs Mounts", description: "In-memory temporary storage" },
  { id: 50, category: "Storage", topic: "Volume Commands", description: "docker volume create/ls/rm/inspect" },
  { id: 51, category: "Storage", topic: "Named vs Anonymous Volumes", description: "Differences and use cases" },
  { id: 52, category: "Storage", topic: "Volume Sharing", description: "Share volumes between containers" },
  { id: 53, category: "Docker Compose", topic: "What is Compose?", description: "Multi-container app definition" },
  { id: 54, category: "Docker Compose", topic: "docker-compose.yml structure", description: "version, services, volumes, networks" },
  { id: 55, category: "Docker Compose", topic: "services", description: "Define each container" },
  { id: 56, category: "Docker Compose", topic: "depends_on", description: "Service startup order" },
  { id: 57, category: "Docker Compose", topic: "environment & env_file", description: "Pass env vars via Compose" },
  { id: 58, category: "Docker Compose", topic: "ports & expose", description: "Port mapping in Compose" },
  { id: 59, category: "Docker Compose", topic: "volumes in Compose", description: "Named volumes & bind mounts" },
  { id: 60, category: "Docker Compose", topic: "networks in Compose", description: "Custom networks in Compose" },
  { id: 61, category: "Docker Compose", topic: "build in Compose", description: "Build from Dockerfile in Compose" },
  { id: 62, category: "Docker Compose", topic: "docker compose up", description: "Start all services" },
  { id: 63, category: "Docker Compose", topic: "docker compose down", description: "Stop & remove all services" },
  { id: 64, category: "Docker Compose", topic: "docker compose build", description: "Build/rebuild services" },
  { id: 65, category: "Docker Compose", topic: "docker compose logs", description: "View service logs" },
  { id: 66, category: "Docker Compose", topic: "docker compose exec", description: "Run command in running service" },
  { id: 67, category: "Docker Compose", topic: "docker compose scale", description: "Scale a service" },
  { id: 68, category: "Docker Compose", topic: "Multiple Compose Files", description: "Override with docker-compose.override.yml" },
  { id: 69, category: "Docker Compose", topic: "Dev vs Prod Compose", description: "Separate configs per environment" },
  { id: 70, category: "Registry", topic: "Docker Hub", description: "Public/private repos on Hub" },
  { id: 71, category: "Registry", topic: "Private Registry", description: "Self-hosted registry (registry image)" },
  { id: 72, category: "Registry", topic: "Cloud Registries", description: "AWS ECR, GCP GCR, Azure ACR" },
  { id: 73, category: "Registry", topic: "Image Versioning", description: "Tagging strategy: latest, semver" },
  { id: 74, category: "Optimization", topic: "Alpine Images", description: "Minimal base images" },
  { id: 75, category: "Optimization", topic: "Minimize Layers", description: "Combine RUN commands" },
  { id: 76, category: "Optimization", topic: "Clean Package Cache", description: "Remove apt/apk cache in same RUN" },
  { id: 77, category: "Optimization", topic: "Build Context Optimization", description: "Use .dockerignore properly" },
  { id: 78, category: "Optimization", topic: "Multi-Stage Builds", description: "Separate build & runtime stages" },
  { id: 79, category: "Optimization", topic: "Image Size Analysis", description: "docker image inspect, dive tool" },
  { id: 80, category: "Security", topic: "Non-root User", description: "Run containers as USER" },
  { id: 81, category: "Security", topic: "Read-only Filesystem", description: "--read-only flag" },
  { id: 82, category: "Security", topic: "Secrets Management", description: "Docker secrets, avoid ENV for secrets" },
  { id: 83, category: "Security", topic: "Image Scanning", description: "docker scout, Trivy, Snyk" },
  { id: 84, category: "Security", topic: "Least Privilege", description: "Drop Linux capabilities" },
  { id: 85, category: "Security", topic: "No Latest Tag in Prod", description: "Always pin image versions" },
  { id: 86, category: "Security", topic: "Resource Limits", description: "--memory, --cpus flags" },
  { id: 87, category: "Docker Swarm", topic: "What is Swarm?", description: "Built-in orchestration" },
  { id: 88, category: "Docker Swarm", topic: "Swarm Init", description: "docker swarm init" },
  { id: 89, category: "Docker Swarm", topic: "Nodes", description: "Manager vs Worker nodes" },
  { id: 90, category: "Docker Swarm", topic: "Services", description: "docker service create/ls/scale" },
  { id: 91, category: "Docker Swarm", topic: "Stacks", description: "Deploy Compose files to Swarm" },
  { id: 92, category: "Docker Swarm", topic: "Rolling Updates", description: "Zero-downtime deployments" },
  { id: 93, category: "Docker Swarm", topic: "Swarm Secrets", description: "Secure secret management" },
  { id: 94, category: "Monitoring", topic: "docker stats", description: "Real-time container metrics" },
  { id: 95, category: "Monitoring", topic: "Docker Events", description: "docker events stream" },
  { id: 96, category: "Monitoring", topic: "Logging Drivers", description: "json-file, syslog, fluentd, splunk" },
  { id: 97, category: "Monitoring", topic: "cAdvisor + Prometheus", description: "Container metrics stack" },
  { id: 98, category: "Monitoring", topic: "Portainer", description: "GUI management for Docker" },
  { id: 99, category: "CI/CD", topic: "Docker in CI/CD", description: "Build & push images in pipelines" },
  { id: 100, category: "CI/CD", topic: "GitHub Actions + Docker", description: "Automate builds on push" },
  { id: 101, category: "CI/CD", topic: "Docker Layer Caching in CI", description: "Speed up CI builds" },
  { id: 102, category: "CI/CD", topic: "Multi-platform Builds", description: "docker buildx, ARM + AMD64" },
  { id: 103, category: "Next Steps", topic: "Kubernetes (K8s)", description: "Container orchestration at scale" },
  { id: 104, category: "Next Steps", topic: "Helm", description: "K8s package manager" },
  { id: 105, category: "Next Steps", topic: "Docker + Terraform", description: "Infrastructure as code" },
  // PHP
  { id: 106, category: "PHP", topic: "Official PHP Images", description: "CLI, Apache, FPM variants" },
  { id: 107, category: "PHP", topic: "PHP Configuration (php.ini)", description: "Customizing settings" },
  { id: 108, category: "PHP", topic: "Installing Extensions", description: "docker-php-ext-install" },
  { id: 109, category: "PHP", topic: "Composer in Docker", description: "Dependency management" },
  { id: 110, category: "PHP", topic: "Xdebug with Docker", description: "Debugging Setup" },
  { id: 111, category: "PHP", topic: "Connecting to Database", description: "MySQL/MariaDB integration" },
  { id: 112, category: "PHP", topic: "Prod vs Dev Images", description: "Optimization strategies" },
  { id: 113, category: "PHP", topic: "Nginx + PHP-FPM", description: "High performance setup" },
  // Laravel
  { id: 114, category: "Laravel", topic: "Laravel Sail", description: "Official dev environment" },
  { id: 115, category: "Laravel", topic: "Manual Dockerfile", description: "Custom setup from scratch" },
  { id: 116, category: "Laravel", topic: "Compose for Laravel", description: "App, DB, Redis, Mailpit" },
  { id: 117, category: "Laravel", topic: "Artisan Commands", description: "Running CLI tools" },
  { id: 118, category: "Laravel", topic: "File Permissions", description: "User/Group issues" },
  { id: 119, category: "Laravel", topic: "Queue Workers", description: "Background processing" },
  { id: 120, category: "Laravel", topic: "Task Scheduling", description: "Cron jobs in Docker" },
  { id: 121, category: "Laravel", topic: "Production Build", description: "Multi-stage optimization" }
];

export const dockerTopics: DockerTopic[] = rawTopics.map(topic => {
  const enriched = enrichedData[topic.id] || {};
  return {
    ...topic,
    longDescription: enriched.longDescription || topic.description + ". (Detailed content pending update).",
    command: enriched.command || `docker ${topic.topic.toLowerCase().split(' ')[0]}`,
    usage: `docker run ${topic.topic.toLowerCase().replace(' ', '-')}`, // Fallback
    tips: [],
    osSpecific: enriched.osSpecific,
    osCommand: enriched.osCommand,
    examples: enriched.examples || [
      {
        title: "Basic Usage",
        code: `# Example command for ${topic.topic}\ndocker ${topic.topic.toLowerCase().split(' ')[0]} --help`,
        description: "Check back soon for detailed examples."
      }
    ]
  };
});
